### ISSUE TITLE
How do you authenticate?

### ISSUE THREAD

**Issue by rossmeissl** [dtmtec/restforce-bulk#2]
I'm used to creating Restforce clients with

``` ruby
client = Restforce.new username: USERNAME,
                       password: PASSWORD,
                       security_token: SECURITY_TOKEN,
                       client_id: CONSUMER_KEY,
                       client_secret: CONSUMER_SECRET
```

and then using `client.describe` etc. to interact with the API. What do I do differently with `Restforce::Bulk`?

**Comment by rossmeissl** [comment]
@gustavokloh any thoughts?

**Comment by gustavokloh** [comment]
@rossmeissl You should do nothing differently.

As you can see here (https://github.com/dtmtec/restforce-bulk/blob/master/lib/restforce/bulk/client.rb#L9)  we use Restforce to authenticate. 

So, if you have the env variables with credentials, that's ok.

**Comment by rossmeissl** [comment]
Thanks @gustavokloh, I was trying to figure out how to declare the auth params in code (versus in the environment), but I gave up and used the [environment auth method](https://github.com/ejholmes/restforce#usernamepassword-authentication) and it worked fine.

**Comment by gustavokloh** [comment]
@rossmeissl :D 

You can declare auth params in code. But you can instantiate the client with params and pass to Restforce::Bulk

I preffer environment vars.
